<a href="https://colab.research.google.com/github/sganguly3000ai/makemore/blob/main/makemore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import torch
torch.manual_seed(42)
ten2 = torch.rand(1,2,32,32)
ten2 = (ten2 - 1) * 2
print(ten2.size())
print (ten2)

x = ten2.size()[1:]
print (f"x => ", x)
features = 1
for s in x:
  features *= s
  print(f"S = ",s)
print (features)





torch.Size([1, 2, 32, 32])
tensor([[[[-0.2355, -0.1700, -1.2343,  ..., -1.9877, -0.0969, -1.8495],
          [-0.2280, -0.8336, -1.3247,  ..., -1.6825, -0.6916, -1.3444],
          [-0.6936, -1.2083, -0.1706,  ..., -0.3202, -1.7252, -1.5339],
          ...,
          [-1.3677, -1.0859, -0.0663,  ..., -1.3775, -0.1739, -0.8977],
          [-1.7479, -0.9937, -1.7767,  ..., -1.2066, -1.0837, -0.5499],
          [-1.1681, -1.8398, -0.1999,  ..., -1.3816, -1.8596, -1.6328]],

         [[-0.4430, -1.1493, -0.5753,  ..., -1.4677, -0.0156, -1.0000],
          [-1.1357, -1.4162, -1.2621,  ..., -0.3510, -0.0893, -0.4164],
          [-1.5183, -1.9890, -0.6207,  ..., -0.2499, -0.4015, -0.6470],
          ...,
          [-1.3201, -1.1368, -1.6700,  ..., -0.8022, -0.3154, -0.5379],
          [-0.6617, -1.3100, -1.8019,  ..., -1.7374, -1.2118, -1.9447],
          [-0.1700, -1.4777, -1.4144,  ..., -0.9756, -0.8182, -0.0575]]]])
x =>  torch.Size([2, 32, 32])
S =  2
S =  32
S =  32
2048


In [2]:
import torch
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import ConcatDataset
transform = transforms.Compose([transforms.ToTensor()])
trainset = torchvision.datasets.CIFAR10(root='./data', train=True,download=True,transform=transform)
#stack all train images together into a tensor of shape #(50000, 3, 32, 32)
x = torch.stack([sample[0] for sample in ConcatDataset([trainset])])

#get the mean of each channel
mean = torch.mean(x, dim=(0,2,3))
print (mean)
#tensor([0.4914, 0.4822, 0.4465])
std = torch.std(x, dim=(0,2,3))
print (std)
#tensor([0.2470, 0.2435, 0.2616])



100%|██████████| 170498071/170498071 [00:03<00:00, 47512328.44it/s]


Extracting ./data/cifar-10-python.tar.gz to ./data
tensor([0.4914, 0.4822, 0.4465])
tensor([0.2470, 0.2435, 0.2616])


In [ ]:
#print (x)
import torch
import numpy as np
import string
"""
t1 = x
t1.shape
tin = x [0,0:3]
#print (f'{tin} and shape {tin.shape}' )
t4 = x[0,0:3,0:32,0:1]
#t5 = x[0,:,:,0:1]
t5 = torch.zeros([3,32,1])
t4t5 = torch.cat((t4,t5),2)
#print (f'test is \n {t4} , {t5} \n shape t4  = {t4.shape} shape t5 = {t5.shape}')
#print (f'test is \n {t4t5} \n shape t4t5  = {t4t5.shape}')
#print (f't4t5 4th column  = {t4t5[:,:,3:4]} {t4t5[:,:,3:4].shape}')

t4t5np = t4t5.numpy()
#print (f'{t4t5np}')
t4t5np = t4t5np[:,:,0:1]

print (f'{t4t5np}')
print (f'{t4t5np.shape}')

t4t5np = t4t5np.flatten('C')
print (f'{t4t5np} {t4t5np.shape}')
t4t5np = t4t5np*10
print (f'{t4t5np} {t4t5np.shape}')
"""
def stoi(x):
  Output = [item[0] for item in chrs
          if item[1] == x]
  return Output

def itos(x):
  Output = [item[1] for item in chrs
          if item[0] == x]
  return Output

b={}
words = ['sumit','sorit','swapna','suraj','sujit', 'sujoy', 'manoj', 'amit',
         'kajol', 'steve', 'andrew','bob', 'cindy']
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1,ch2 in zip(chs, chs[1:]):
    bigram = (ch1,ch2)
    b[bigram] = b.get(bigram,0) + 1
    #print (bigram)
    #print (type(bigram))
sorted(b.items(), key = lambda kv: -kv[1])
chrs = list(string.ascii_lowercase)
chrs = list(enumerate(chrs))
chrs.insert(26, (26, '.'))
print (chrs)
#print (stoi('b'))
#print (itos (25))





In [134]:
import torch
import numpy as np
import string
"""
t1 = x
t1.shape
tin = x [0,0:3]
#print (f'{tin} and shape {tin.shape}' )
t4 = x[0,0:3,0:32,0:1]
#t5 = x[0,:,:,0:1]
t5 = torch.zeros([3,32,1])
t4t5 = torch.cat((t4,t5),2)
#print (f'test is \n {t4} , {t5} \n shape t4  = {t4.shape} shape t5 = {t5.shape}')
#print (f'test is \n {t4t5} \n shape t4t5  = {t4t5.shape}')
#print (f't4t5 4th column  = {t4t5[:,:,3:4]} {t4t5[:,:,3:4].shape}')

t4t5np = t4t5.numpy()
#print (f'{t4t5np}')
t4t5np = t4t5np[:,:,0:1]

print (f'{t4t5np}')
print (f'{t4t5np.shape}')

t4t5np = t4t5np.flatten('C')
print (f'{t4t5np} {t4t5np.shape}')
t4t5np = t4t5np*10
print (f'{t4t5np} {t4t5np.shape}')
"""
def stoi(x):
  Output = [item[0] for item in chrs
          if item[1] == x]
  return Output

def itos(x):
  Output = [item[1] for item in chrs
          if item[0] == x]
  return Output
b ={}
N = torch.zeros((27,27) , dtype = torch.int32)
words = ['sumit','sorit','swapna','suraj','sujit', 'sujoy', 'manoj', 'amit',
         'kajol', 'steve', 'andrew','bob', 'cindy', 'ebrahim', 'daku']
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1,ch2 in zip(chs, chs[1:]):
    bigram = (ch1,ch2)
    N[stoi(ch1),stoi(ch2)] = N[stoi(ch1),stoi(ch2)] + 1
    #b[bigram] = b.get(bigram,0) + 1
    #print (bigram)
    #print (type(bigram))
sorted(b.items(), key = lambda kv: -kv[1])
chrs = list(string.ascii_lowercase)
chrs = list(enumerate(chrs))
chrs.insert(26, (26, '.'))
#print (stoi('s'))
#print (itos (25))
print (N[18])

[18]
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 4, 0, 1, 0,
        0, 0, 0], dtype=torch.int32)
